WebApplication1/Controllers/LoginController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using System.Web.Security;
using WebApplication1.Models;

namespace WebApplication1.Controllers
{
    public class LoginController : Controller
    {
        private MVCAppDatabaseEntities db = new MVCAppDatabaseEntities();

        // GET: Login
        [AllowAnonymous]
        public ActionResult Index()
        {
            return View();
        }

        [HttpPost]
        [AllowAnonymous]
        public ActionResult Index(UserModel User)
        {
            if (!ModelState.IsValid)
            {
                ViewBag.Message = "Invalid Login Details";
                return View();
            }

            var user = from s in db.Users
                       join y in db.Roles
                       on s.RoleId equals y.id
                       where s.Name == User.Name && s.password == User.password
                       select new { id = s.id, Name = s.Name, RoleId = s.RoleId, RoleName = y.Name };

            if (user == null)
            {
                return View();
            }
            if (user.Count() > 0)
            {
                if (user.SingleOrDefault().RoleName == "Admin")
                {
                    ViewBag.Message = "";
                    FormsAuthentication.SetAuthCookie(User.Name, false);
                    var authTicket = new FormsAuthenticationTicket(1, user.SingleOrDefault().Name, DateTime.Now, DateTime.Now.AddMinutes(20), false, user.SingleOrDefault().RoleName);
                    string encryptedTicket = FormsAuthentication.Encrypt(authTicket);
                    var authCookie = new HttpCookie(FormsAuthentication.FormsCookieName, encryptedTicket);
                    HttpContext.Response.Cookies.Add(authCookie);

                    return RedirectToAction("Index", "Home");
                }
            }

            ViewBag.Message = "Invalid Login Details";
            return View();
        }
    }
}

WebApplication1/Views/Login/Index.cshtml
@model WebApplication1.Models.UserModel

@{
    Layout = null;
}

<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title>Login</title>
    <link href="//maxcdn.bootstrapcdn.com/bootstrap/4.1.1/css/bootstrap.min.css" rel="stylesheet" id="bootstrap-css">
    <script src="//maxcdn.bootstrapcdn.com/bootstrap/4.1.1/js/bootstrap.min.js"></script>
    <script src="//code.jquery.com/jquery-1.11.1.min.js"></script>
    @Styles.Render("~/Content/login")

</head>
<body>
    @*@using (Html.BeginForm("Index", "Login", FormMethod.Post))
        {*@
    <div class="container">
        <div id="login-row" class="row justify-content-center align-items-center">
            <div id="login-column" class="col-md-6">
                <div class="box">
                    <div class="shape1"></div>
                    <div class="shape2"></div>
                    <div class="shape3"></div>
                    <div class="shape4"></div>
                    <div class="shape5"></div>
                    <div class="shape6"></div>
                    <div class="shape7"></div>
                    <div class="float">
                        <form class="form" method="post">
                            <div class="form-group">
                                <label for="username" class="text-white">Username:</label><br>
                                @Html.EditorFor(model => model.Name, new { htmlAttributes = new { @class = "form-control" } })
                                @Html.ValidationMessageFor(model => model.Name, "", new { @class = "text-danger" })

                                @*<input type="text" name="username" id="username" class="form-control">*@
                            </div>
                            <div class="form-group">
                                <label for="password" class="text-white">Password:</label><br>
                                @*<input type="text" name="password" id="password" class="form-control">*@
                                @Html.EditorFor(model => model.password, new { htmlAttributes = new { @class = "form-control" } })
                                @Html.ValidationMessageFor(model => model.password, "", new { @class = "text-danger" })
                                @ViewBag.Message
                            </div>
                            <div class="form-group">
                                
                                <input type="submit" name="submit" class="btn btn-info btn-md" value="submit">
                            </div>
                        </form>
                    </div>
                </div>
            </div>
        </div>
    </div>
    @* } *@
</body>
</html>